### ISSUE TITLE
Required types not allowed

### ISSUE THREAD

**Issue by gonzauy** [vega/ts-json-schema-generator#1980] opened 2024-05-29 21:16 UTC
Hi 👋 all !

We have two type cases where the JSON schema output seems to be not good:

```
export type ReqAll<T> = Required<
  {
    [P in keyof T]: ReqAll<T[P]>;
  }
>;

export type WithReq<T, K extends keyof T> = T & { [P in K]-?: T[P] };

export type Ab = { a?: string; b?: boolean };

export type Ra = {
  ra: ReqAll<Ab>;
  wr: WithReq<Ab, 'a'>;
};
```

The generated schema for `Ra` type is:

```
{
  "$ref": "#/definitions/Ra",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Ra": {
      "additionalProperties": false,
      "properties": {
        "ra": {
          "$ref": "#/definitions/ReqAll%3CAb%3E"
        },
        "wr": {
          "$ref": "#/definitions/WithReq%3CAb%2C%22a%22%3E"
        }
      },
      "required": [
        "ra",
        "wr"
      ],
      "type": "object"
    },
    "ReqAll<(boolean|undefined)>": {
      "additionalProperties": false,
      "type": "object"
    },
    "ReqAll<(string|undefined)>": {
      "additionalProperties": false,
      "type": "object"
    },
    "ReqAll<Ab>": {
      "additionalProperties": false,
      "properties": {
        "a": {
          "$ref": "#/definitions/ReqAll%3C(string%7Cundefined)%3E"
        },
        "b": {
          "$ref": "#/definitions/ReqAll%3C(boolean%7Cundefined)%3E"
        }
      },
      "type": "object"
    },
    "WithReq<Ab,\"a\">": {
      "additionalProperties": false,
      "properties": {
        "a": {
          "type": "string"
        },
        "b": {
          "type": "boolean"
        }
      },
      "type": "object"
    }
  }
}
```

Would you mind to help us with this case? Is there any workaround?

Many thanks!

**Comment by domoritz** [comment] 2024-05-29 21:24
Duplicate of #189

**Closed as not planned** 2024-05-29 21:24 UTC
