### ISSUE TITLE
Generation without tsconfig

### ISSUE THREAD

**Issue by havsar** [vega/ts-json-schema-generator#1439] opened 2022-10-13 18:23 UTC
Is there a possibility to generate schemas without using the .ts source files and the tsconfig json?

This could be useful for the case when schema generation is required at runtime. At runtime, we often don't have the tsconfig and ts source files available, .d.ts files at most.

Can this library work just with the emitted metadata at runtime?

**Comment by domoritz** [comment] 2022-10-16 13:44
Duplicate of https://github.com/vega/ts-json-schema-generator/pull/1386

**Closed as completed by domoritz** 2022-10-16 13:44 UTC
