### ISSUE TITLE
Issue when attempting to generate a schema from a type, conflict with @types/glob dependencies

### ISSUE THREAD

**Issue by DelliriumX** [vega/ts-json-schema-generator#1875] opened 2024-02-21 13:54 UTC
I am creating an npm package which exposes some scripts to be used as a CLI tool.
As part of this project, i am using **ts-josn-schema-generator** to create a schema for configurations that the CLI uses.
In my CLI's project, when I run the scripts, tests, whatever else, it all works fine.
However when I install that package as a dependency of another package (my main project), the scripts no longer work.

I keep getting an error when I attempt to make a generator from a config.

This is the error:

> Error: Namespace '"...MyProjectFolder.../node_modules/minimatch/dist/cjs/index"' has no exported member 'IOptions'.
> 
> '"...MyProjectFolder.../node_modules/minimatch/dist/cjs/index"' has no exported member named 'IMinimatch'. Did you mean 'Minimatch'?
> 
> Private identifiers are only available when targeting ECMAScript 2015 and higher.
> 

this is the script used to generate the schema in my CLI's code:

```
export const SCHEMA_TYPE_NAME = 'ICFG' as const

export function generateTypeSchema(filepath: string, type = SCHEMA_TYPE_NAME) {
  const config = {
    path: filepath,
    type: type,
  }
  const generator = tsj.createGenerator(config)  // THIS LINE CAUSES AN ERROR
  const schema = generator.createSchema(type)
  return schema
}
```

### EDIT: 
Upon further investigation, the issue due to existence of `"@types/glob": "^8.1.0",` as a dependency in the project, when this dependency is removed, the script runs fine, with it present we get an error. I've checked that package and it's own dependencies are `@types/minimatch`. I dont know where the conflict is, but its something I need help with

**Comment by DelliriumX** [comment] 2024-03-05 19:41
I've resorted to removing the conflicting package, but the issue persists, I do not know what to do. It might help someone in the future to figure out what the issue is.

I will abandon this post now, seeing as there are no replies :(

**Comment by domoritz** [comment] 2024-03-05 20:04
Hmm, not sure how to help but it looks like the issue is in minimatch so should probably be raised there. I'll close this issue but feel free to add anything you learn.

**Closed as completed by domoritz** 2024-03-05 20:04 UTC
