### ISSUE TITLE
Interfaces methods mapping in a json schema

### ISSUE THREAD

**Issue by paztis** [vega/ts-json-schema-generator#470] opened 2020-07-24 14:45 UTC
Is there a way to define methods of an interface inside a json schema ?
for example 
```
export interface A {
   prop1: string;
   method1(param1: string): string;
}
```

only generates 
```
{
    "A": {
      "type": "object",
      "properties": {
        "prop1": {
          "type": "string"
        }
    }
}
```

Is there a valid json schema way to provide something like this ?

```
{
  "IApi": {
    "type": "object",
    "properties": {
      "prop1": {
        "type": "string"
      },
      "methods": {
        "method1": {
          "type": "object",
          "properties": {
            "parameters": {
              "type": "array",
              "items": {
                ...
              }
            },
            "return": {
              "type": ...
            }
          }
        }
      }
    }
  }
}
```

I try to model methods in the standard of schema, but didn't know if it is possible

**Comment by domoritz** [comment] 2020-07-24 14:55
Duplicate of https://github.com/vega/ts-json-schema-generator/issues/98

**Closed by domoritz** 2020-07-24 14:55 UTC
