### ISSUE TITLE
[REG 1.0->1.1] Properties not applied from value type

### ISSUE THREAD

**Issue by orgads** [vega/ts-json-schema-generator#1431] opened 2022-10-02 17:55 UTC
```typescript
type UrlTypes = {

  /**
   * @pattern ^https:\/\/.*$
   */
  url: string;
}

interface AllFields {
  field1: string;
  field2: string;
}

type UrlFields = {
  [key in keyof AllFields]?: UrlTypes['url'];
};

export interface Test {
  foo?: UrlFields;
}
```

Running:
`npx ts-json-schema-generator --no-type-check --path schema-test.ts --type Test --validation-keywords patternProperties --out schema-test.json`

The output is missing the pattern in v1.1.2. This is the output from v1.0.0, and I'm marking the lines that are missing:
```json
{
  "$ref": "#/definitions/Test",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Test": {
      "additionalProperties": false,
      "properties": {
        "foo": {
          "additionalProperties": false,
          "properties": {
            "field1": {
              "pattern": "^https:\\/\\/.*$", // <---------- This is missing
              "type": "string"
            },
            "field2": {
              "pattern": "^https:\\/\\/.*$", // <---------- This is missing
              "type": "string"
            }
          },
          "type": "object"
        }
      },
      "type": "object"
    }
  }
}
```

**Comment by domoritz** [comment] 2022-10-16 13:52
Thanks for noting the regression. Can you identify the change that caused this so we can either fix it or revert the change?

**Comment by orgads** [comment] 2022-10-18 06:10
c5f3ef96189c7ed4c2279189bf03e6db57018206.

```
c5f3ef96189c7ed4c2279189bf03e6db57018206 is the first bad commit
commit c5f3ef96189c7ed4c2279189bf03e6db57018206
Author: Filipe Pomar <filipomar@hotmail.com>
Date:   Sun Jul 31 16:09:46 2022 +0200

    fix: support valid circular reference breaking the parsing process (#1263)

 factory/parser.ts                                  |  4 +-
 src/NodeParser/IndexedAccessTypeNodeParser.ts      | 33 ++++++++++++++--
 src/NodeParser/TypeReferenceNodeParser.ts          |  6 +--
 test/valid-data-type.test.ts                       |  1 +
 .../type-indexed-circular-access/main.ts           | 12 ++++++
 .../type-indexed-circular-access/schema.json       | 46 ++++++++++++++++++++++
 6 files changed, 93 insertions(+), 9 deletions(-)
 create mode 100644 test/valid-data/type-indexed-circular-access/main.ts
 create mode 100644 test/valid-data/type-indexed-circular-access/schema.json
bisect found first bad commit
```

**Comment by orgads** [comment] 2023-01-19 16:13
ping?

**Comment by domoritz** [comment] 2023-01-19 17:16
Thanks for digging into the issue. Can you look into a fix? I don't have cycles right now to dig into it unfortunately.

**Comment by arthurfiorette** [comment] 2024-05-29 02:48
Duplicate of https://github.com/vega/ts-json-schema-generator/issues/189

Will work again once:

```ts
type UrlFields = {
  [key in keyof AllFields]?: UrlTypes['url'];
//                        ~
};
```

gets fixed

**Closed as completed by arthurfiorette** 2024-05-29 02:48 UTC
