### ISSUE TITLE
Basic Usage Fails

### ISSUE THREAD

**Issue by GordonSmith** [vega/ts-json-schema-generator#140] opened 2019-06-22 08:24 UTC
First time user and very likely a setup / dependency issue, but the following is failing:

```
./node_modules/.bin/ts-json-schema-generator --path tmp.ts --type Test
```

Working Directory:
```
~/git/hpcc-js/packages/ddl-shim
```

Where tmp.ts is
```javascript
export interface Test {
    test: boolean;
}
```

And the output errors are:
```
$ ./node_modules/.bin/ts-json-schema-generator --path tmp.ts --type Test
Users/gordon/git/hpcc-js/node_modules/@types/request/index.d.ts(66,15): error TS2430: Interface 'DefaultUriUrlRequestApi<TRequest, TOptions, TUriUrlOptions>' incorrectly extends interface 'RequestAPI<TRequest, TOptions, TUriUrlOptions>'.
  Types of property 'defaults' are incompatible.
    Type '(options: TOptions) => DefaultUriUrlRequestApi<TRequest, TOptions, OptionalUriUrl>' is not assignable to type '{ (options: TOptions): RequestAPI<TRequest, TOptions, RequiredUriUrl>; (options: (UriOptions & TOptions) | (UrlOptions & TOptions)): DefaultUriUrlRequestApi<TRequest, TOptions, OptionalUriUrl>; }'.
      Type 'DefaultUriUrlRequestApi<TRequest, TOptions, OptionalUriUrl>' is not assignable to type 'RequestAPI<TRequest, TOptions, RequiredUriUrl>'.
        Types of property 'delete' are incompatible.
          Type '{ (uri: string, options?: TOptions, callback?: RequestCallback): TRequest; (uri: string, callback?: RequestCallback): TRequest; (options: OptionalUriUrl & TOptions, callback?: RequestCallback): TRequest; }' is not assignable to type '{ (uri: string, options?: TOptions, callback?: RequestCallback): TRequest; (uri: string, callback?: RequestCallback): TRequest; (options: (UriOptions & TOptions) | (UrlOptions & TOptions), callback?: RequestCallback): TRequest; }'.
            Types of parameters 'options' and 'options' are incompatible.
              Type '(UriOptions & TOptions) | (UrlOptions & TOptions)' is not assignable to type 'OptionalUriUrl & TOptions'.
                Type 'UriOptions & TOptions' is not assignable to type 'OptionalUriUrl & TOptions'.
                  Type 'UriOptions & TOptions' is not assignable to type 'OptionalUriUrl'.
                    Types of property 'uri' are incompatible.
                      Type 'string | Url' is not assignable to type 'string'.
                        Type 'Url' is not assignable to type 'string'.
```

Note:  it looks like its trying to parse stuff from node_modules in the parent/parent folder unnecessarily?

**Comment by GordonSmith** [comment] 2019-06-22 08:40
Workaround:  I created a new tsconfig-schema.json file:
```
{
    "compilerOptions": {},
    "include": [
        "./tmp.ts"
    ]
}
```

And updated my call to:
```
./node_modules/.bin/ts-json-schema-generator --path tsconfig-schema.json --type Test
```

**Comment by kayahr** [comment] 2019-06-22 15:24
Looks like it parses all type definitions in `node_modules/@types/*` and in in your project there is a problem in some file (Which is explained by the error message). I see two more workarounds:

1. Run the schema generator with `--no-type-check` option.

2. Run the schema generator outside of your project:

    ```
    ddl-shim/node_modules/.bin/ts-json-schema-generator --path ddl-shim/tmp.ts --type Test
    ```
But all these workarounds sucks...

@domoritz I think it could be fixed by adding `typeRoots: []` [here](https://github.com/vega/ts-json-schema-generator/blob/master/factory/program.ts#L45). But I'm not sure if this won't break other things. But at least it would be consistent then. When path is a typescript file then @types directory is always ignored, no matter from where the generator is started. And when path is a tsconfig.json then it does whatever is defined there.

**Comment by domoritz** [comment] 2019-06-22 19:21
I think the default type roots are a good default since otherwise, we won't be able to compile many programs. Ideally, we would get both a tsconfig file (to set the compile options) and a path to a file that we should start parsing from. 

Another option is for us to just look for the closest tsconfig file in the path and use that. 

Either way, the original issue is not a bug in our library since the types are invalid. I will file a new issue to see how we can improve how we get compile options.

**Closed by domoritz** 2019-06-22 19:21 UTC
