### ISSUE TITLE
Error "… are only available when targeting ECMAScript 20XX and higher" when targetting ESNext

### ISSUE THREAD

**Issue by zefir-git** [vega/ts-json-schema-generator#1580] opened 2023-02-23 17:23 UTC
Hello,
In my `tsconfig.json` I have `target: esnext` and `module: esnext`, `moduleResolution: node` etc, regardless, I am getting errors such as these:
```
error TS18028: Private identifiers are only available when targeting ECMAScript 2015 and higher.
error TS1259: Module '"node:path"' can only be default-imported using the 'esModuleInterop' flag
```
etc. I also get these errors for files in 3rd party libraries in `node_modules`.

If I add `-f tsconfig.json` to the command, all of these errors disappear, but are replaced with this error for every file in my project:
```
TS6307 file is not listed within the file list of project 'tsconfig.json'. Projects must list all files or use an 'include' pattern
```

My tsconfig has an include pattern that covers all `.ts` file in the project. Explicitly adding a file in `files` does not work either.

What am I doing wrong here?

**Comment by arthurfiorette** [comment] 2023-02-23 22:48
Are you using the extends flag in your `tsc`? Can you provide your tsconfig or a reproducible repository?

**Comment by zefir-git** [comment] 2023-02-24 10:36
> Are you using the extends flag in your `tsc`? Can you provide your tsconfig or a reproducible repository?

Not sure what this flag is. I have `noEmitHelpers: true` which "disables generating custom helper functions like '__extends' in compiled output".

Here is my tsconfig
```json
{
    "include": [
        "src/**/*.ts"
    ],
    "exclude": [
        "node_modules"
    ],
    "compilerOptions": {
        "incremental": true,
        "composite": true,
        "target": "esnext",
        "module": "ESNext",
        "moduleResolution": "node",
        "declaration": true,
        "declarationMap": true,
        "sourceMap": true,
        "outDir": "./",
        "stripInternal": true,
        "noEmitHelpers": true,
        "noEmitOnError": true,
        "allowSyntheticDefaultImports": true,
        "esModuleInterop": true,
        "preserveSymlinks": true,
        "forceConsistentCasingInFileNames": true,
        "strict": true,
        "noImplicitAny": true,
        "strictNullChecks": true,
        "strictFunctionTypes": true,
        "strictBindCallApply": true,
        "strictPropertyInitialization": true,
        "noImplicitThis": true,
        "alwaysStrict": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "noImplicitReturns": true,
        "noUncheckedIndexedAccess": true,
        "noImplicitOverride": true,
        "allowUnreachableCode": false,
        "skipDefaultLibCheck": true,
        "skipLibCheck": true
    },
    "tsc-alias": {
        "resolveFullPaths": true
    }
}
```

I created a blank repository and used this same tsconfig and it appears to work. Not sure what the breaking difference between it and my actual repository might be. Any clue based on the errors?

**Comment by zefir-git** [comment] 2023-02-24 14:34
It looks like as soon as I add any sort of `import` it breaks with something like
```
home/user/project/src/test/index.ts(1,15): error TS6307: File '/home/user/project/src/a.ts' is not listed within the file list of project 'tsconfig.json'. Projects must list all files or use an 'include' pattern.
```
project root is `/home/user/project` and tsconfig file has include patterns `src/**/*.ts` & `src/*.ts` and builds successfully with `tsc`

**Comment by arthurfiorette** [comment] 2023-02-24 14:41
@williamd5, `noImportHelpers` is actually allowing it to use the functions but does not import them or generates the code, you're looking for `importHelpers: false`. But I don't know if this will fix your issue. Can you open a reproducible repository so I can test it out too?

**Comment by zefir-git** [comment] 2023-02-24 15:48
@arthurfiorette `importHelpers: false` did not fix it. Here is a repo: https://github.com/williamd5/test-ts-json-schema-generator

I added a `npm test` script which runs the cmd and shows the error

**Comment by zefir-git** [comment] 2023-03-01 09:02
Were you able to reproduce this?

**Comment by ntippie** [comment] 2023-04-26 22:48
`tsconfig.build.json`
```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "composite": false
  }
}
```
`$ ts-json-schema-generator -f ./tsconfig.build.json`

This resolved it for me.

**Comment by arthurfiorette** [comment] 2023-04-26 22:53
@williamd5, did the @ntippie fix resolved for you?

**Comment by zefir-git** [comment] 2023-04-28 19:01
> @williamd5, did the @ntippie fix resolved for you?

will test when I can. So what is causing the issue is using composite builds?

**Comment by arthurfiorette** [comment] 2024-05-29 02:28
Closing this PR since I couldn't reprouce the issue. Feel free to reopen if needed.

**Closed as completed by arthurfiorette** 2024-05-29 02:28 UTC

**Comment by Bejasc** [comment] 2024-06-08 01:44
@zefir-git did you have any resolution for this?

I am having the same issue - `composite: false` and `importHelpers: false` did not make any difference for me.

When building with tsc, I have no errors.

However when running the command `npx ts-json-schema-generator --path 'src/types/EventSystem/IEventBase.ts' --type 'IEventBase' --out 'schemas/eventSchema.json'` - I have around 30 TS errors that are logged into the console - the majority of these actually being reported inside of `node_modules`

I have tried disabling all extensions and various tweaks to my .tsconfig, without any luck.

```json
{
	"compilerOptions": {
		"module": "commonjs",
		"target": "es2022",
		"rootDir": "src",
		"tsBuildInfoFile": "dist/.tsbuildinfo",
		"outDir": "dist",
		"lib": ["ESNext", "ESNext.Array", "ESNext.AsyncIterable", "ESNext.Intl", "ES2015.Symbol", "DOM"],
		"sourceMap": true,
		"inlineSources": true,
		"incremental": true,
		"esModuleInterop": true,
		"experimentalDecorators": true,
		"emitDecoratorMetadata": true,
		"resolveJsonModule": true,
		"skipLibCheck": true,
	},
	"include": ["src/**/*", "/src/data/**/*.json"],
	"exclude": ["node_modules", "GPT Helper"]
}
```

---

Take note the "GPT Helper" file - which lives outside of my src directory. When I use this file as a target - the output works fine and the schema is saved to the out file, with no errors generated.

The file that is used in the GPT Helper directory and the file that is used inside the src are the same.

@arthurfiorette FYI

**Comment by Bejasc** [comment] 2024-06-08 01:47
Most of the errors generated when running the command aren't even consistent with my tsconfig. Here's a collection of them 

```
swrpg-bot-v2/node_modules/@discordjs/rest/dist/index.d.ts(753,5): error TS18028: Private identifiers are only available when targeting ECMAScript 2015 and higher.
swrpg-bot-v2/node_modules/@discordjs/ws/dist/index.d.ts(68,5): error TS18028: Private identifiers are only available when targeting ECMAScript 2015 and higher.
swrpg-bot-v2/node_modules/@discordjs/ws/dist/index.d.ts(616,5): error TS18028: Private identifiers are only available when targeting ECMAScript 2015 and higher.
swrpg-bot-v2/node_modules/@sapphire/discord.js-utilities/dist/cjs/index.d.cts(802,5): error TS18028: Private identifiers are only available when targeting ECMAScript 2015 and higher.
swrpg-bot-v2/node_modules/@sapphire/pieces/dist/index.d.ts(413,5): error TS18028: Private identifiers are only available when targeting ECMAScript 2015 and higher.
swrpg-bot-v2/node_modules/@sapphire/pieces/dist/index.d.ts(576,5): error TS18028: Private identifiers are only available when targeting ECMAScript 2015 and higher.
swrpg-bot-v2/node_modules/@sapphire/snowflake/dist/cjs/index.d.cts(8,33): error TS2737: BigInt literals are not available when targeting lower than ES2020.
swrpg-bot-v2/node_modules/@sapphire/snowflake/dist/cjs/index.d.cts(12,34): error TS2737: BigInt literals are not available when targeting lower than ES2020.
swrpg-bot-v2/node_modules/@sapphire/snowflake/dist/cjs/index.d.cts(16,34): error TS2737: BigInt literals are not available when targeting lower than ES2020.
swrpg-bot-v2/node_modules/drpg-economy/dist/classes/DrpgEconomy.d.ts(2,10): error TS2305: Module '"../types/IEconomyConfig"' has no exported member 'CurrencyString'.
swrpg-bot-v2/node_modules/drpg-economy/dist/Index.d.ts(4,10): error TS2305: Module '"./classes/TradeRumor"' has no exported member 'generateTradeRumor'.
swrpg-bot-v2/src/functions/CombatSystem/CombatantPlayer.ts(127,27): error TS2340: Only public and protected methods of the base class are accessible via the 'super' keyword.
swrpg-bot-v2/src/functions/CombatSystem/DeathHandler.ts(7,8): error TS1259: Module '"F:/Discord Bots/SWRPG/swrpg-bot-v2/node_modules/moment/ts3.1-typings/moment"' can only be default-imported using the 'esModuleInterop' flag        
swrpg-bot-v2/src/functions/DrpgEvent/DrpgTimer.ts(4,8): error TS1259: Module '"F:/Discord Bots/SWRPG/swrpg-bot-v2/node_modules/moment/ts3.1-typings/moment"' can only be default-imported using the 'esModuleInterop' flag
swrpg-bot-v2/src/lib/PersistentStorage.ts(1,8): error TS1192: Module '"fs"' has no default export.
swrpg-bot-v2/src/services/CharacterSystem/EffectService.ts(10,8): error TS1259: Module '"F:/Discord Bots/SWRPG/swrpg-bot-v2/node_modules/moment/ts3.1-typings/moment"' can only be default-imported using the 'esModuleInterop' flag    
swrpg-bot-v2/src/services/Discord/GuildMemberHelper.ts(4,8): error TS1259: Module '"F:/Discord Bots/SWRPG/swrpg-bot-v2/node_modules/moment/ts3.1-typings/moment"' can only be default-imported using the 'esModuleInterop' flag
swrpg-bot-v2/src/services/EventSystem/DrpgEventSystem.ts(11,8): error TS1259: Module '"F:/Discord Bots/SWRPG/swrpg-bot-v2/node_modules/moment/ts3.1-typings/moment"' can only be default-imported using the 'esModuleInterop' flag      
swrpg-bot-v2/src/services/EventSystem/EventBuilder.ts(378,34): error TS2550: Property 'replaceAll' does not exist on type 'string'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2021' or later.
swrpg-bot-v2/src/services/EventSystem/EventBuilder.ts(384,34): error TS2550: Property 'replaceAll' does not exist on type 'string'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2021' or later.
swrpg-bot-v2/src/services/InventoryService.ts(279,42): error TS2802: Type 'Map<ICharacter, InventorySpace>' can only be iterated through when using the '--downlevelIteration' flag or with a '--target' of 'es2015' or higher.
swrpg-bot-v2/src/services/ShipyardService.ts(193,46): error TS2550: Property 'replaceAll' does not exist on type 'string'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2021' or later.      
swrpg-bot-v2/src/services/ShipyardService.ts(196,72): error TS2550: Property 'replaceAll' does not exist on type 'string'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2021' or later.      
swrpg-bot-v2/src/services/TravelService.ts(8,8): error TS1259: Module '"F:/Discord Bots/SWRPG/swrpg-bot-v2/node_modules/moment/ts3.1-typings/moment"' can only be default-imported using the 'esModuleInterop' flag
swrpg-bot-v2/src/types/CombatSystem/ProceduralAttackText.ts(415,4): error TS2550: Property 'replaceAll' does not exist on type 'string'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2021' or later.
```

**Comment by zefir-git** [comment] 2024-10-01 21:27
@Bejasc sorry for the late response. Sadly, I don't have a resolution. I either wrote a schema manually or scrapped the idea.
